### ISSUE TITLE
Default behaviour for remote contents that can not be splitted

### ISSUE THREAD

**Issue by k0pernicus** [derniercri/snatch#20]
`Snatch` is a tool that download efficiently a remote content, splitting this one into chunks and download each of those in a thread.

But, there can exists some problems if the server canno't send in a request the length of the remote content, or if the server does not use HTTP 1.1 (+).
If the program meet those "problems", it stops.
But, is a default behaviour for those remote contents can be to download the remote content, in a single thread?

**Comment by Jean-Serge** [comment]
Yes but with an info for the user like :
`Multi-thread download is not available on the remote server, starting mono-thread downloading.`

I mean not really this sentence but you see what I mean

**Comment by k0pernicus** [comment]
I agree 👍 
It could be a gretter behaviour than stoping the program...

**Comment by Jean-Serge** [comment]
I've created an issue about it can we close this one ?
