### ISSUE TITLE
Installation documentation needs to be updated

### ISSUE THREAD

**Issue by Outpox** [derniercri/snatch#54]
Hey there, I wanted to give snatch a try and so I followed the README to install it.  

It it suggested to do as follow : `cargo install --git https://github.com/derniercri/snatch.git` but once installed I noticed that it was the `master` version which got installed since:  

```
▶ snatch -V       
Usage:
    snatch [OPTIONS]
snatch: Unknown short option "V"
```  
  
So I deleted it and reinstalled it with `cargo install --git https://github.com/derniercri/snatch.git --branch devel` and it solved it for me. :-)  
```
▶ snatch -V
Snatch 0.1.2
```

**Comment by k0pernicus** [comment]
Hi @Outpox,
Thank you for this issue :-)
I will update the documentation this afternoon ;-)

**Comment by k0pernicus** [comment]
According to the work of @xvw (#54), the documentation has been updated ;-)
Thanks a lot again @Outpox and @xvw !
