### ISSUE TITLE
Show net down speed

### ISSUE THREAD

**Issue by mufasa71** [derniercri/snatch#59]
It would be nice to know total download speed, as well as size of already downloaded content.

**Comment by k0pernicus** [comment]
Hello,
No problem, I'll add that feature this week-end ;-)

**Comment by k0pernicus** [comment]
Hey @mukimov,
actually, this feature has already been added in the last version of the `devel` branch.
Are you using the `master` version of _Snatch_ ?

**Comment by mufasa71** [comment]
Hi @k0pernicus I don't see any changes on `devel` branch. I don't see total speed and total downloaded size. I only see speed for each chunk.
![image](https://i.imgur.com/A9svC9t.png, '')
Did I miss something? Thank you!

**Comment by k0pernicus** [comment]
Oh sorry @mukimov, I didn't see that you wanted the total informations.
Great idea - I label this issue for the next release ;-)
