### ISSUE TITLE
Alternate progress indicator like axel

### ISSUE THREAD

**Issue by mitnk** [derniercri/snatch#60]
Hi, I like this tool! very cool!

It would be nice if snatch could provide a alternate progress bar like the `-a` option in tool `axel`. Because I will use `snatch -t40` or `-t50` to download big stuff, and the screen cannot fit all that many separated progress bars :)

Thanks!

**Comment by k0pernicus** [comment]
Hi @mitnk - thank you for this issue.
It's ok, we will try to update the progress bar for the next release :-)
