### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by messense** [derniercri/snatch#63]
https://crates.io/search?q=snatch

If you want to grab the name `snatch` on crates.io.

Also it would be easier for others to install it by:

```bash
cargo install snatch
```

**Comment by k0pernicus** [comment]
Yep, we plan to publish the next release version of _Snatch_ on cargo ;-)

**Comment by k0pernicus** [comment]
Hi @messense, the current `devel` version of _Snatch_ in [on crates.io](https://crates.io/crates/snatch) now :-)
Thank you again !
