### ISSUE TITLE
Use Indicatif

### ISSUE THREAD

**Issue by xvw** [derniercri/snatch#75]
To try to keep snatch "simple as possible", could we maybe use https://github.com/mitsuhiko/indicatif instead of a custom "progress bar implementation" ?

**Comment by equal-l2** [comment]
This project never uses 'a custom "progress bar implementation"' but uses `pbr`.
Is there any merit with switching to `indicatif`?

**Comment by xvw** [comment]
Hum, my bad :) 
Sorry for that.
